### ISSUE TITLE
Update Form component to better support Netlify Form

### ISSUE THREAD

**Issue by max8hine** [batchnz/gatsby-starter#15]
@hatzipanis I am adding an issue we've been discussing in another project.

Now Netlify has an [official guide](https://www.netlify.com/blog/2017/07/20/how-to-integrate-netlifys-form-handling-in-a-react-app/#form-handling-with-static-site-generators) for integrating with their form service, our current form could be improved by the guide. We've done this with Cobalt already so we could reference [this code](https://gitlab.com/batchnz/work/cobalt001/blob/master/src/components/Footer/Form/index.js).

**Comment by hatzipanis** [comment]
This was completed in #16.
