### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by max8hine** [batchnz/gatsby-starter#16]

**Comment by max8hine** [comment]
Details

The Screenshot of [Upgrating details](https://user-images.githubusercontent.com/15165714/64495474-e787d900-d2ee-11e9-9781-c591a62f8bd7.png)

The packages major versions have been jumped:

1.  **gatsby-plugin-offline** v2 -> v3
2.  **gatsby-plugin-purgecss** v3 -> v4
3.  **postcss-extend-rule** v2 -> v3
4.  **stylelint** v9 -> v10
5.  **stylelint-config-prettier** v4 -> v5
6.  **tailwindcss** v0.6.6 -> v1.1.2

**Comment by max8hine** [comment]
Hi, @hatzipanis, The task has been completed and tested in both Local and server.

Wating for code-review from https://github.com/batchnz/gatsby-starter/pull/17

**Comment by hatzipanis** [comment]
Thanks @max8hine this has been merged in.
